# Generated by Django 5.1 on 2024-11-18 12:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('escola', '0004_alter_curso_codigo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='estudante',
            name='data_nascimento',
            field=models.DateField(default='2000-01-01'),
        ),
    ]
